name: mobx_hooks
description: Flutter Hooks for Mobx
version: 0.0.3
homepage: https://github.com/yiss/mobx_hooks

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # MobX is a library for reactively managing the state of your applications. Use the power of observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^2.1.3
  # Flutter integration for MobX. It provides a set of Observer widgets that automatically rebuild when the tracked observables change.
  flutter_mobx: ^2.0.6+5
  # A flutter implementation of React hooks. It adds a new kind of widget with enhanced code reuse.
  flutter_hooks: ^0.18.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
